version: '3.5'

services:
  fuseki:
    image: stain/jena-fuseki
    container_name: fuseki
    restart: always
    volumes:
      - rdf_data:/fuseki
      - staging:/staging
    ports:
      - "3030:3030"
    expose:
      - "3030"
    networks:
      - semapps
    environment:
      ADMIN_PASSWORD: "admin"

  middleware:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: middleware
    restart: always
    depends_on:
      - fuseki
    volumes:
      - ./:/app
    networks:
      - semapps
    ports:
      - "3000:3000"
    expose:
      - "3000"

volumes:
  rdf_data:
  staging:
networks:
  semapps:
    name: semapps_network
